// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoListAPI.Data;

#nullable disable

namespace TodoListAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TodoListAPI.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Critical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "High"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 5,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("TodoListAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        },
                        new
                        {
                            Id = 3,
                            Name = "guest"
                        },
                        new
                        {
                            Id = 4,
                            Name = "moderator"
                        },
                        new
                        {
                            Id = 5,
                            Name = "superuser"
                        });
                });

            modelBuilder.Entity("TodoListAPI.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(2182),
                            Description = "Desc 1",
                            DueDate = new DateTime(2025, 12, 25, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(2324),
                            IsCompleted = false,
                            PriorityId = 1,
                            Title = "Task 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3071),
                            Description = "Desc 2",
                            DueDate = new DateTime(2025, 12, 26, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3071),
                            IsCompleted = false,
                            PriorityId = 2,
                            Title = "Task 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3075),
                            Description = "Desc 3",
                            DueDate = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3076),
                            IsCompleted = true,
                            PriorityId = 3,
                            Title = "Task 3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3077),
                            Description = "Desc 4",
                            DueDate = new DateTime(2025, 12, 27, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3078),
                            IsCompleted = false,
                            PriorityId = 4,
                            Title = "Task 4",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3080),
                            Description = "Desc 5",
                            DueDate = new DateTime(2025, 12, 29, 12, 37, 12, 626, DateTimeKind.Utc).AddTicks(3080),
                            IsCompleted = false,
                            PriorityId = 5,
                            Title = "Task 5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("TodoListAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 11, 962, DateTimeKind.Utc).AddTicks(3730),
                            Email = "admin@example.com",
                            Login = "admin",
                            PasswordHash = "$2a$11$gHz6CDY3qFxYid3ddhl1XOoNbY2L5pKmA88p4PCsIVLcIaozmwFUu",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 136, DateTimeKind.Utc).AddTicks(125),
                            Email = "user1@example.com",
                            Login = "user1",
                            PasswordHash = "$2a$11$Go9gf7B8fACKkniSkC8jLOYpi8Vyfi8ovFKJ3KzSSR5.AZG3xUSZa",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 265, DateTimeKind.Utc).AddTicks(9892),
                            Email = "user2@example.com",
                            Login = "user2",
                            PasswordHash = "$2a$11$rL22Dk3Lk6lamISmU7V81OZwSPma2G6Bp2w9hzFMVMkOXdH13BdH2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 388, DateTimeKind.Utc).AddTicks(2511),
                            Email = "user3@example.com",
                            Login = "user3",
                            PasswordHash = "$2a$11$ZW1r.PlyOlTmwUpXRELBSeKWtOLywuiw8m5xkIZUmel03KOmkTIYC",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 37, 12, 510, DateTimeKind.Utc).AddTicks(5346),
                            Email = "user4@example.com",
                            Login = "user4",
                            PasswordHash = "$2a$11$HLx95fM1/.ua5KrrVfx3ReftNhvho0vkJOAIDj8zLfPxhW5PTBUDe",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("TodoListAPI.Models.TodoItem", b =>
                {
                    b.HasOne("TodoListAPI.Models.Priority", "Priority")
                        .WithMany("TodoItems")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoListAPI.Models.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoListAPI.Models.User", b =>
                {
                    b.HasOne("TodoListAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TodoListAPI.Models.Priority", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("TodoListAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TodoListAPI.Models.User", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
